sudo: required
services:
  - docker

before_install:
  - docker build -t paladinze/react_playground -f Dockerfile.dev .

script:
  - docker run -e CI=true paladinze/react_playground npm run test -- --coverage
